README.md
it got to big and to time consuming -> it got too big and too time consuming
=> Fix typo: to -> too

index.html
Added information in the index.html file for the portfolio for #2
=> Added information in the portfolio page

README.md
According to #13 I added a small reminder 🌟
=> Add a star to the end of README

index.html, styles.css
Added some colors and icons to the footer
=> CSS coloring and icons

index.html
=> added font awesome icons for social media handles and enabled the links to open in new tab

index.html, styles.css
Added the necessary meta viewport tag.
=> Fix erorrs in console, fix css error, adjusted social media links

index.html
=> Add Another Skills

app.js, index.html, styles.css
I was create a stagger animation for the list content.
=> Create stagger animation for content (#43)

index.html
=> Remove duplicate fontawesome link

app.js, index.html, styles.css
Profile Picture spins if you click it 10 times.
=> Add Easter Egg

styles.css
=> Show nav bar above text

styles.css
=> fix(styles): add z-index to fix issue #56

app.js, index.html
Hover over The number 3 in footer to see the magic
=> Added hidden Messages a.k.a Easter Eggs In the Website

index.html, styles.css
Added a zoom animation on the name, and icons for social media when hover
=> Animation zoom on hover

index.html
fixed About link, cleaned up html - removed doubles of each section.
=> Clean up index

index.html, styles.css
Added a link to the github repository of your project.
=> Add Link to Github Repository

index.html
=> removed duplicate header

app.js, index.html, styles.css
Change the sentences if you like! I hope it's funny! 🤣
=> Add Typed.js animation.

index.html
Added a repo link as icon to keep the design of the website clean
Related Issue #71
=> added repo-link as icon

index.html, styles.css
Add smooth scroling and change style a little bit.
Every portpholio must have some work examples.
=> minor fixes

styles.css
I thought it would be nice if the Profile picture spins on hover :)
=> let the profile picture spin on hover

index.html, styles.css
- Removed from a wrapper to separate from the main content to reposition the header outside the main content.
- Remove the extra header. For some reason you had two headers.
=> Reposition header to sit next to the body

styles.css
- Profile Image in the body of the site is now centered
- Looks pretty good until window.innerWidth is less than 504(px)
=> Centered Profile Image

index.html
Header section was duplicated, so I removed it
=> removed extra profile picture

index.html, styles.css
#92 also fixed the profile being too far to the right
=> fixed horizontal position of the header

index.html, styles.css
"about myself" was not aligned properly.
=> location of "about myself"

styles.css
- Added background color animation
=> Modified Background

app.js, index.html, styles.css
If a user clicks the `O` in `ABOUT MYSELF`, it will increment the size of the profile img. If a user cliks the `o` in `Software`, it will decrement the size of the profile img.
=> easter egg: increase/decrease profile img size

.vscode/settings.json, index.html
Fixed the logo image and profile image.
=> fixed broken logo image and profile image

styles.css
Changed the header styles and position the left sidebar properly.
=> Fixed left sidebar issue

index.html, styles.css
This repo looks fun! 
This PR contains changes:
- Change style of `Skills` section
- Remove duplicated skills content
=> Change style of `Skills` section

index.html
For some reason the skill list seemed to be duplicated and contained different skills. I merged them into one.
=> Merged duplicate skill list

app.js, index.html
This PR adds in https://github.com/jlengstorf/honkify. It's a fun little gag.
=> Add honkify

index.html, styles.css
divided the long list into sub lists, updated some other Areas of Interest, added CSS styling to changes
=> Content updates of base page after LinkedIn Review

app.js
Another Easter Egg???!! 
Enter the konami code (↑↑↓↓←→←→BA) to flip the body element. 
Do it twice to return to normal.
=> add a konami code easter egg. 

index.html
Created id for contact to allow smooth scroll to contact section of the page.
=> allow smooth scroll to contact information

animation/BennyAnimationStyle.css, index.html, styles.css
Added the animation on the animation folder to the profile section of the site. Made a mistake on first commit and modified a line in the BennyAnimationStyle.css, I returned it to its original state on my second commit, in case anyone else wants to use the animation elsewhere.
=> Added BennyCarlsson animation to profile section of portfolio

app.js
Another easter egg was added that broke the konami code, the original event listener had been removed.
Merging the two easter eggs under the same event listener so they work together. This is serious stuff, we can't have any bugs here!
=> Merge konami code and hitchhikers guide

index.html
=> updated text about me (#133)

app.js
=> Added F to pay respect.

styles.css
love the idea!
I added a little animation to the social icons.
=> social icons are jumping up and down now

index.html
=> fixed spelling and text styling

index.html, styles.css
changing the previous "#home" to "#" will directly take you to top of page otherwise this was not functioning once you scroll down somewhere.
=> changing link of home button on home page

images/rc-logo.svg, index.html, styles.css, vanilla-tilt.js
Added some fun tilt animations using the Vanilla Tilt js library. Also added a resilient coders ASCII art easter egg animation for fun. :)
Vanilla Tilt JS:
https://micku7zu.github.io/vanilla-tilt.js/
Resilient Coders:
http://www.resilientcoders.org/
Thank you for letting us have fun with your portfolio!
=> Add tiltjs and resilient easter egg

styles.css
=> fixed padding on numbers on footer

index.html
I've improved the information to better sell your skills as per #133 by rewriting some of the text to look more professional, mentioned your numerous Github projects and changed the list layout slightly.
=> Improved Information to Sell Skills

app.js, index.html, styles.css
Add scroll to top button solving issue [132](https://github.com/BennyCarlsson/MyPortfolio-Hacktoberfest2019/issues/132)
=> add scroll to top button

styles.css
added a hot pink text selection highlight
=> added text selection highlight

index.html
With the message "Welcome to my portfolio" to display a message that this is the portfolio page, below the navigation menu
=> Added H1 tag

app.js, index.html
Click on "CSS" under "Web Technologies" ; )
=> Comic-Sansify the Webpage.

styles.css
I changed the normal cursor-pointer for a custom one. I might edit the hover cursor later, or feel free to do it. I can send psd file if needed
=> changed normal pointer for a more amazing one

app.js, styles.css
also added a star wars easter egg
=> modified some css for the header as the spacing was odd

styles.css
deleted lines that were commented out and unused and made the colour of the hyperlink related to Benny's email the same as the about me.
=> deleted commented out lines and changed colour of hyperlink

animation/BennyAnimationStyle.css
First time in my whole two weeks of programming working with anything like this, thanks for the opportunity  :P :D
=> color changes in slide animation

index.html, styles.css
=> Contact-form

index.html, styles.css
hello.I made some changes in the website.
=> made submit button cursor pointer type and modified heading

index.html
this is a fun idea I hope you do it next year.
=> fixed capitalization errors and added homer at the bottom

README.md
Everyone knows the most important part of a project is the stuff the user never sees! Gotta start with a good foundation. 😎
=> Update README spelling and grammar

index.html, styles.css
=> better header i think

index.html, styles.css
Shifted options to left and Added a Beautiful name at the center of header
#183
=> Tweaked the header

index.html, styles.css
Easter egg position, fixed header and some minor layout changes.
=> Layout changes

app.js
Add a small animation to the wizard
=> Animated Wizard

README.md
Very minor README.md fixes. Hopefully this doesn't come across as a petty PR.
Still learning open-source & coding, so sticking to documentation PRs for now.
Happy Hacktober & thanks for the opportunity :D
=> Minor grammar & spelling correction in README.md

index.html, styles.css
Here is my contribution. It's not much because I'm still a beginner but I tried my best.
=> simple css update

index.html
=> Remove duplicate stylesheet reference

index.html, styles.css
This stretches the navbar making it look less out of place on larger screens.
=> Make the navbar stretch the whole length of the window

styles.css
=> Update line 17

index.html, styles.css
It didn't do anything previously.
=> Make home button bring you to the top of the page

index.html, styles.css
New kind of async jump effect for social links
=> style: async jump animation

animation/BennyAnimationStyle.css, index.html, styles.css
https://github.com/BennyCarlsson/MyPortfolio-Hacktoberfest2019/issues/204
I cleaned up to the best of my knowledge, there can still be some code that can be removed.
=> Cleaned up unused CSS and merged header/body tag code together, also removed some unused CSS/HTML relating to typed

styles.css
#206 changed lighter background color
=> Lighter background colour

index.html
So that job offerings will be a streamlined process. Use it or change it!
Happy hacking!
#hacktoberfest
=> Added mailto: feature

app.js, index.html
Added the necessary "Hello World" Javascript example when clicking on the JavaScript link.
Happy coding!
#hacktoberfest
=> Added javascript example

animation/title.css, index.html
as the title explains I've just made an animation on the main title that starts at the hover. 
cheers
=> animated title (main h1 my portfolio)

index.html, styles.css
- added titles to menu links (on mobile you can't tell what the links are otherwise)
- centered social icons on mobile (so it matches on desktop)
=> Mobile fixes

js/app.js
=> :rainbow: Rainbow easter egg added - press r to see the magic!

css/styles.css, index.html
=> New branch

index.html
With the "correct" spelling of "favoUrite" and "coloUr"
=> added favourite colour input on 'reach us' page

index.html
Using tholman/github-corner, added a small graphic to top right of index.html that will take users to the GitHub repo for the project
=> Added github corner to profile

index.html
Added a link to your university so everyone could check it out! (I think I messed up the commit earlier?)
=> Added link to your University

index.html
=> Update index.html text

index.html
Jazzed up the wordings in the portfolio owner's story + add link to his university 🥇 👍
=> Spruce up the story and added a link to the university.

css/styles.css, index.html
I've fixed the responsive issues. 
As the nav li span was set to display none in media queries. I removed it as it was blocking the display of text "Home", "Info" and "Reach us" when open in mobile devices.
=> Fixed the Responsive Issues. [Added Bootstraps Files]

css/styles.css, index.html
I've added some awesome styling to the 'My Story' heading which includes a delicious colour scheme. Removed the marquee styling on the BennyCarlsonGif as it didn't load on my browser. Hope this helps Benny.
=> Add awesome styling to the My Story heading

css/styles.css
=> fix page scroll

index.html
Made the site a little more friendly.
=> Added a welcoming note

css/styles.css
Added shake effect and rotation
=> Added effects to the navbar

index.html
Add Google maps link to hometown and a link to email id in basic info section
=> Add links to basic info

css/styles.css, index.html
-Added a soft skills list
-Added another achievement as a c-c-c-c-combo breaker 
-Removed an empty css ruleset
=> Added additional text content to skills section

index.html
Unless you has to has too many has!
=> deleted extra has, because cant has too many has

css/styles.css
1. Updated the class _my-name_ with background-color and color on hover.
2. Updated the class _the-my-story-heading-class_ with color and font-weight
3. Updated the class _this-div_ with background-color
=> Updated CSS for some classes

index.html
Added the link for ### **SnakeGame.html** which is submitted under MyPortfolio-Hacktoberfest2019
=> Added link for SnakeGame in index

css/styles.css
header alignment to match git fork ribbon
=> header alignment to match git fork ribbon

index.html
Added embeeded tweets, fixed padding, added Testimonials
=> Added embeeded tweets, fixed padding, added Testimonials

css/styles.css, index.html
- improve design with adding some comic sanse when hovering specific text
- improve readability with align some text to the right
=> Improve design

index.html
Links with target blank were missing rel attribute with noreferrer value and the referred information was passed to the website being linked. Also, the page can be controlled from the new website being linked because no opener value was missing from the rel attribute. This is a security approach because links to the cross-origin destinations are unsafe. Read more on below link:
https://developers.google.com/web/tools/lighthouse/audits/noopener 
Fixed some a tag missing > character and image tag missing alt attribute.
=> Made some improvement on index file

index.html, js/app.js
I tried playing with the Fetch api to load a new set of pictures every 30 seconds, but ran into cors issues.
Anyways, nice website! :)
=> Added 3 random pictures!

index.html
There was double html navigation tag in index.html
=> fix(double nav): removing double navigation from html

css/styles.css, index.html
Benny is a catalyst for change in a divided world - he's been converting people from light mode to dark and back again for as long as he's known the difference, and it's about time this amazing work was acknowledged from a satisfied client.
=> Add more high-quality testimonials

index.html
Organized an HTML file section (list of technologies and development methodologies)
=> cleaned up html structure and clarified experience section

js/app.js
✅ Ready to merge !
ADD : On each keydown event on inputs, background color change to another pink color (#232)
=> ✅ ADD 232 Design : random pink color on inputs

index.html
I updated the Favorite Spelling in the index .html
=> Favorite Spelling

index.html
=> issue-resolved #296

index.html
This will comment out the duplicated svg image. specifically the image that was appearing at the bottom.
=> comment out lower duplicated github svg

index.html
Hi! I have made very few changes to the text by reducing the redundancy of some text and have given few indentation to the text without using pretty printing text software! Hope this will do the work and you'd merge :)
=> Text changed with better grammer and indentation

index.html
=> Added "letter of recommendation" to index.html

README.md
I have corrected a couple of spelling and other mistakes. Hope you have fun with all the Hacktoberfest and good luck.
=> corrected a couple of mistakes

index.html
This PR cleans up a lot of the markup on the page and is related to issue [#305 ](https://github.com/BennyCarlsson/MyPortfolio-Hacktoberfest2019/issues/305)
=> Cleanup markup and badly formatted attributes

css/styles.css, index.html
Added an important achievement of yours - wedding photographer, and your fabulous wedding photography portfolio to prove it!
=> added achievement + work to prove it 

index.html
i have removed duplicate side bar and clean up some code.
=> removed duplicate side bar

css/styles.css, style/main.css
I have updated the background of 2048 game.
=> Change 20148  games background

index.html
*Added elon musks picture link to the text , because it's necessary for everyone to know how he looks
*Made the visitor count who visit the end of the page bold because it wouldn't matter or else
=> Necessary changes
